### PR TITLE
Merg Zerbaib

### PR DESCRIPTION
**Pull request by Zerbaib**
all commit a remove at this [**commit**](https://github.com/Zerbaib/BotDiscordTemplateDev/commit/9cce5204a8225d1434fb7872456a6cc14f6f68d5)

### CODE REVIEW

**Comment by Zerbaib** [comment]
@Person0z what Feature you need ?

**Comment by Person0z** [comment]
> @Person0z what Feature you need ?

Probally, ill add NJR, I'm thinking of doing ``/radio country:America/Mexica/France radio:Radio - America, Radio - Mexico, Radio - France.``

**Comment by Zerbaib** [comment]
i think i have better country:
- America
- France
- Spanish

but it's okay for me to do that
i going to check

**Comment by Zerbaib** [comment]
i have added a reaction at the hello message

is not in general.py beacause the ``on_message`` event was already there

**Comment by Person0z** [comment]
You don't need the f string on the print function when it notifies that the cog is loaded. Why make a completely new file for welcome / byes? That goes under general since it's not well big enough to need its own file. What's the reason for adding a hello cog? We don't need the bot to say hello to people, that's a useless feature to say. and adding the NJR is gonna be done by doing ```/radio country:France station:NJR```

**Comment by Zerbaib** [comment]
> You don't need the f string on the print function when it notifies that the cog is loaded. Why make a completely new file for welcome / byes? That goes under general since it's not well big enough to need its own file. What's the reason for adding a hello cog? We don't need the bot to say hello to people, that's a useless feature to say. and adding the NJR is gonna be done by doing `/radio country:France station:NJR`

The problem is that in a python code we couldn't put the same event twice (on_message) so I had to create another one to get it
and the command / radio I would not know how I could do that I look of course but it is a rather complex command

**Comment by jaymaart** [comment]
> 

ive already done it, if you wanna take a look at the PRs you can see there.

**Comment by Zerbaib** [comment]
> > 
> 
> ive already done it, if you wanna take a look at the PRs you can see there.

okay thx

now i recreate the level cog but i have a probleme in ``on_message`` in the xp give:

 the xp donation works well but the problem is that it does not add up to the one before

**Comment by Zerbaib** [comment]
i do this commit ``ebbff`` because I started from the logic that we log the arrival and departure

**Comment by Zerbaib** [comment]
i think the pull can merge now

**Comment by Zerbaib** [comment]
Quite simply because it is already there in the logging file

**Review by Zerbaib — COMMENTED** [review]
done

**Review by Zerbaib — COMMENTED** [review]
I have finish to code now go to merge

**Comment by Zerbaib** [comment]
i have create a security for invite link

**Review by Zerbaib — COMMENTED** [review]
I think you can merge it's i have create good feature

**Comment by Zerbaib** [comment]
with this commit i have created a good help sys for the rank sys

**Comment by Zerbaib** [comment]
with this i have a sys to log edited message

**Comment by Zerbaib** [comment]
now we can chose what user you want to see level;

On write of the command:
image

With no option:
image

With option:
image

**Comment by Zerbaib** [comment]
But i want to set user mention and i don't a the code for this

**Comment by Zerbaib** [comment]
but the code is work

**Comment by Person0z** [comment]
i will look into adding this

**Comment by Zerbaib** [comment]
nicee

**Pull request closed without merging**
